-- MySQL Script generated by MySQL Workbench
-- Sat May 31 15:08:51 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema vetlink
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vetlink
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vetlink` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `vetlink` ;

-- -----------------------------------------------------
-- Table `vetlink`.`_prisma_migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vetlink`.`_prisma_migrations` (
  `id` VARCHAR(36) NOT NULL,
  `checksum` VARCHAR(64) NOT NULL,
  `finished_at` DATETIME(3) NULL DEFAULT NULL,
  `migration_name` VARCHAR(255) NOT NULL,
  `logs` TEXT NULL DEFAULT NULL,
  `rolled_back_at` DATETIME(3) NULL DEFAULT NULL,
  `started_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `applied_steps_count` INT UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `vetlink`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vetlink`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `vetlink`.`plans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vetlink`.`plans` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  `price` FLOAT NOT NULL,
  `period` VARCHAR(50) NOT NULL,
  `trialPeriod` INT NULL DEFAULT '0',
  `isActive` TINYINT(1) NOT NULL DEFAULT '1',
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `roleId` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `roleId` (`roleId` ASC) VISIBLE,
  CONSTRAINT `plans_ibfk_1`
    FOREIGN KEY (`roleId`)
    REFERENCES `vetlink`.`roles` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `vetlink`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vetlink`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `planId` INT NOT NULL,
  `roleId` INT NOT NULL,
  `terms` TINYINT(1) NOT NULL DEFAULT '0',
  `isProfileComplete` TINYINT(1) NULL DEFAULT '0',
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `isTrial` TINYINT(1) NULL DEFAULT '1',
  `trialStartedAt` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `trialEndsAt` DATETIME NULL DEFAULT NULL,
  `planExpiresAt` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `planStartedAt` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  INDEX `planId` (`planId` ASC) VISIBLE,
  INDEX `roleId` (`roleId` ASC) VISIBLE,
  CONSTRAINT `users_ibfk_1`
    FOREIGN KEY (`planId`)
    REFERENCES `vetlink`.`plans` (`id`),
  CONSTRAINT `users_ibfk_2`
    FOREIGN KEY (`roleId`)
    REFERENCES `vetlink`.`roles` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `vetlink`.`owners`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vetlink`.`owners` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `lastName` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(50) NOT NULL,
  `secondaryPhone` VARCHAR(50) NULL DEFAULT NULL,
  `city` VARCHAR(255) NOT NULL,
  `neighborhood` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL,
  `userId` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `userId` (`userId` ASC) VISIBLE,
  CONSTRAINT `owners_ibfk_1`
    FOREIGN KEY (`userId`)
    REFERENCES `vetlink`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `vetlink`.`pets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vetlink`.`pets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `species` VARCHAR(100) NOT NULL,
  `breed` VARCHAR(100) NOT NULL,
  `sex` VARCHAR(20) NOT NULL,
  `birthDate` DATETIME NOT NULL,
  `color` VARCHAR(100) NOT NULL,
  `microchipNumber` VARCHAR(100) NULL DEFAULT NULL,
  `tattooCode` VARCHAR(100) NULL DEFAULT NULL,
  `passportNumber` VARCHAR(100) NULL DEFAULT NULL,
  `codeVetlink` VARCHAR(100) NOT NULL,
  `sterilized` TINYINT(1) NOT NULL DEFAULT '0',
  `allergies` TEXT NULL DEFAULT NULL,
  `chronicDiseases` TEXT NULL DEFAULT NULL,
  `disabilities` TEXT NULL DEFAULT NULL,
  `bloodType` VARCHAR(20) NULL DEFAULT NULL,
  `behaviorNotes` TEXT NULL DEFAULT NULL,
  `feedingSchedule` TEXT NULL DEFAULT NULL,
  `diet` VARCHAR(100) NULL DEFAULT NULL,
  `activityLevel` VARCHAR(50) NOT NULL,
  `aggressive` VARCHAR(20) NOT NULL,
  `ownerId` INT NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL,
  `photo` TEXT NULL DEFAULT NULL,
  `favoriteFood` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `pets_codeVetlink_key` (`codeVetlink` ASC) VISIBLE,
  INDEX `ownerId` (`ownerId` ASC) VISIBLE,
  CONSTRAINT `pets_ownerId_fkey`
    FOREIGN KEY (`ownerId`)
    REFERENCES `vetlink`.`owners` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `vetlink`.`dewormings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vetlink`.`dewormings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `petId` INT NOT NULL,
  `product` VARCHAR(255) NOT NULL,
  `date` DATETIME NOT NULL,
  `nextDate` DATETIME NULL DEFAULT NULL,
  `notes` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `petId` (`petId` ASC) VISIBLE,
  CONSTRAINT `dewormings_petId_fkey`
    FOREIGN KEY (`petId`)
    REFERENCES `vetlink`.`pets` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `vetlink`.`documents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vetlink`.`documents` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `petId` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `fileUrl` VARCHAR(512) NOT NULL,
  `type` VARCHAR(100) NOT NULL,
  `uploadDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `notes` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `petId` (`petId` ASC) VISIBLE,
  CONSTRAINT `documents_petId_fkey`
    FOREIGN KEY (`petId`)
    REFERENCES `vetlink`.`pets` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `vetlink`.`features`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vetlink`.`features` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `createAt` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `planId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `planId` (`planId` ASC) VISIBLE,
  CONSTRAINT `features_ibfk_1`
    FOREIGN KEY (`planId`)
    REFERENCES `vetlink`.`plans` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 46
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `vetlink`.`medications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vetlink`.`medications` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `petId` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `dosage` VARCHAR(100) NOT NULL,
  `frequency` VARCHAR(100) NOT NULL,
  `startDate` DATETIME NOT NULL,
  `endDate` DATETIME NULL DEFAULT NULL,
  `prescribedBy` VARCHAR(255) NULL DEFAULT NULL,
  `notes` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `petId` (`petId` ASC) VISIBLE,
  CONSTRAINT `medications_petId_fkey`
    FOREIGN KEY (`petId`)
    REFERENCES `vetlink`.`pets` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `vetlink`.`vaccines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vetlink`.`vaccines` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `petId` INT NOT NULL,
  `vaccineType` VARCHAR(100) NOT NULL,
  `date` DATETIME NOT NULL,
  `batchNumber` VARCHAR(100) NULL DEFAULT NULL,
  `vetName` VARCHAR(255) NULL DEFAULT NULL,
  `notes` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `petId` (`petId` ASC) VISIBLE,
  CONSTRAINT `vaccines_petId_fkey`
    FOREIGN KEY (`petId`)
    REFERENCES `vetlink`.`pets` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
